using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace WastedBridge.OfflineChecks
{
    /// <summary>
    /// Generates the stand-in ScriptHookVDotNet3 assembly's source from the <em>real</em> pinned
    /// SHVDN DLL's metadata.
    ///
    /// Why a stand-in exists at all: the pinned SHVDN nightly is an x64 PE for .NET Framework and
    /// arm64 CoreCLR refuses to load it (BadImageFormatException), so WastedBridge.dll cannot
    /// resolve its GTA types on this machine. The stub carries the same assembly identity and the
    /// one type the off-server code paths touch — GTA.VehicleDrivingFlags — with member values
    /// copied verbatim out of the real DLL's metadata (read here with MetadataLoadContext, which
    /// does not execute the image). Nothing is hand-written, and nothing is deployed: the game
    /// server loads the real SHVDN.
    /// </summary>
    internal static class StubGenerator
    {
        private const string EnumTypeName = "GTA.VehicleDrivingFlags";

        /// <summary>The member the drift stub renumbers, and by how much.</summary>
        private const string DriftMember = "DrivingModeStopForVehicles";
        private const uint DriftDelta = 1;

        public static int Run(string[] args)
        {
            bool drift = Array.IndexOf(args, "--drift") >= 0;
            string outPath = args.Length > 1 && !args[1].StartsWith("--")
                ? args[1]
                : Path.Combine(Paths.ToolRoot, drift ? "shvdn-stub-drift" : "shvdn-stub",
                    "VehicleDrivingFlags.g.cs");

            if (!File.Exists(Paths.RealShvdnDll))
            {
                Console.Error.WriteLine("FATAL: " + Paths.RealShvdnDll + " is missing. It is "
                    + "gitignored third-party content; fetch it with scripts/fetch-shvdn.ps1 "
                    + "(or unzip lib/ScriptHookVDotNet-v3.7.0-nightly.189.zip) and retry.");
                return 2;
            }

            AssemblyName identity;
            List<KeyValuePair<string, ulong>> members;
            string underlying = ReadEnum(Paths.RealShvdnDll, out identity, out members);
            string sha = Sha256(Paths.RealShvdnDll);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// GENERATED — do not edit by hand. Regenerate with:");
            sb.AppendLine("//     bridge/tools/offline-checks/run.sh");
            sb.AppendLine("// Source of every value below: bridge/lib/ScriptHookVDotNet3.dll");
            sb.AppendLine("//     assembly : " + identity);
            sb.AppendLine("//     sha256   : " + sha);
            sb.AppendLine("//     type     : " + EnumTypeName + " (underlying " + underlying + ")");
            sb.AppendLine("//     read with System.Reflection.MetadataLoadContext (metadata only;");
            sb.AppendLine("//     the x64 PE is never executed on this host).");
            if (drift)
            {
                sb.AppendLine("//");
                sb.AppendLine("// DRIFT FIXTURE: " + DriftMember + " is deliberately renumbered by +"
                              + DriftDelta + " below. This is the negative case for");
                sb.AppendLine("// DrivingStyles.Verify() — a guard that cannot fail is not a guard,");
                sb.AppendLine("// so the offline checks require Verify() to report drift against it.");
            }
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace GTA");
            sb.AppendLine("{");
            sb.AppendLine("    [System.Flags]");
            sb.AppendLine("    public enum VehicleDrivingFlags : " + underlying);
            sb.AppendLine("    {");
            foreach (KeyValuePair<string, ulong> m in members)
            {
                ulong value = m.Value;
                bool renumbered = drift && m.Key == DriftMember;
                if (renumbered)
                {
                    value += DriftDelta;
                }
                sb.Append("        ").Append(m.Key).Append(" = ")
                  .Append(value.ToString(CultureInfo.InvariantCulture)).Append(',');
                if (renumbered)
                {
                    sb.Append(" // renumbered from ")
                      .Append(m.Value.ToString(CultureInfo.InvariantCulture))
                      .Append(" on purpose (drift fixture)");
                }
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(outPath));
            File.WriteAllText(outPath, sb.ToString());
            Console.WriteLine("wrote " + outPath + " (" + members.Count + " members from "
                              + identity.Name + " " + identity.Version + ", sha256 "
                              + sha.Substring(0, 16) + "…" + (drift ? ", DRIFT fixture" : "") + ")");
            return 0;
        }

        /// <summary>Reads the enum's members straight out of the real DLL's metadata.</summary>
        public static string ReadEnum(string dllPath, out AssemblyName identity,
                                      out List<KeyValuePair<string, ulong>> members)
        {
            var searchPaths = new List<string> { dllPath };
            searchPaths.AddRange(Directory.GetFiles(
                System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory(), "*.dll"));

            using (var mlc = new MetadataLoadContext(new PathAssemblyResolver(searchPaths),
                                                     "System.Private.CoreLib"))
            {
                Assembly asm = mlc.LoadFromAssemblyPath(dllPath);
                identity = asm.GetName();
                Type t = asm.GetType(EnumTypeName, true);

                members = new List<KeyValuePair<string, ulong>>();
                foreach (FieldInfo f in t.GetFields(BindingFlags.Public | BindingFlags.Static))
                {
                    members.Add(new KeyValuePair<string, ulong>(
                        f.Name, Convert.ToUInt64(f.GetRawConstantValue(),
                                                 CultureInfo.InvariantCulture)));
                }
                return t.GetEnumUnderlyingType().Name == "UInt32" ? "uint"
                     : t.GetEnumUnderlyingType().Name == "Int32" ? "int"
                     : t.GetEnumUnderlyingType().Name.ToLowerInvariant();
            }
        }

        public static string Sha256(string path)
        {
            using (var sha = SHA256.Create())
            using (FileStream fs = File.OpenRead(path))
            {
                return BitConverter.ToString(sha.ComputeHash(fs)).Replace("-", "").ToLowerInvariant();
            }
        }
    }
}
