"""Harness models vs the bridge's REAL serialized output (CONTRACTS v1.2).

This is the cross-package test. Everything else in this suite checks the harness
against the harness's own idea of the contract — which is exactly how
`last_task.id: null` got all the way to delivery day: both packages were
internally consistent and disagreed with each other.

The inputs here are the bridge package's own recordings in
``bridge/contract-samples/``: JSON produced by *its compiled DLL* (the same
``SnapshotJson.Serialize`` the game thread publishes ``/state`` with) and by its
real ``BridgeRouter`` over a real HTTP connection. They are bridge output, not
fixtures anybody typed, so a shape drift on either side fails here — in CI, on a
laptop — instead of at 3am on the server.

Deliberately NOT copied into ``harness/tests/fixtures/``: that directory is
reserved for recordings of real game sessions (CLAUDE.md rule 1). These are read
from the bridge path, and the whole module skips with a clear message when the
bridge package is absent.

What these samples are and are not: field names, nesting, JSON types and null
handling are real (produced by the compiled assembly). The world *values*
(coordinates, street names) are assembled by the bridge's own tool because
natives cannot run off the game server. So this file asserts shapes, types and
nullability — never that a number means anything about the game world.
"""

from __future__ import annotations

import json
import os
import random
import socket
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, ClassVar

import pytest

from wasted_harness.behavior.activities import ActivityPicker, ActivityRunner
from wasted_harness.behavior.recovery import (
    GameRestartDetector,
    StrandedEscalator,
    StuckDetector,
    flipped_action,
)
from wasted_harness.bridge_client import (
    BRIDGE_ERROR_STATUS,
    KNOWN_EDITIONS,
    TRANSIENT_BRIDGE_ERRORS,
    BridgeApiError,
    BridgeClient,
    BridgeTransientError,
    GameState,
    Health,
    OnlineSessionActiveError,
    classify_bridge_error,
)
from wasted_harness.perception import Perceptor

# --- locating the bridge's recordings -----------------------------------------

SAMPLES_DIR = Path(
    os.environ.get(
        "WASTED_BRIDGE_SAMPLES",
        Path(__file__).resolve().parents[2] / "bridge" / "contract-samples",
    )
)

_SKIP_REASON = (
    f"bridge contract samples not found at {SAMPLES_DIR}. They are generated by "
    f"bridge/tools/offline-checks/run.sh from the compiled WastedBridge.dll. "
    f"Without them the harness cannot check its models against real bridge bytes; "
    f"regenerate them in the bridge package, or point WASTED_BRIDGE_SAMPLES at them."
)

pytestmark = pytest.mark.skipif(not SAMPLES_DIR.is_dir(), reason=_SKIP_REASON)


def _raw(name: str) -> bytes:
    path = SAMPLES_DIR / name
    if not path.exists():
        pytest.skip(f"{path} missing — regenerate with bridge/tools/offline-checks/run.sh")
    return path.read_bytes()


def _load(name: str) -> Any:
    return json.loads(_raw(name))


# --- key coverage --------------------------------------------------------------


def _keys(node: Any, prefix: str = "") -> set[str]:
    """Every dotted key path in a JSON document (list items collapse to [])."""
    out: set[str] = set()
    if isinstance(node, dict):
        for k, v in node.items():
            path = f"{prefix}.{k}" if prefix else k
            out.add(path)
            out |= _keys(v, path)
    elif isinstance(node, list):
        for item in node:
            out |= _keys(item, f"{prefix}[]")
    return out


# --- /state --------------------------------------------------------------------


def test_first_poll_of_a_session_validates() -> None:
    """The document that used to crash the harness on its very first poll.

    `last_task.id` and `last_task.type` are null until a task has been posted
    (CONTRACTS v1.2 (a)); the harness's model declared them as required `str`.
    """
    state = GameState.model_validate(_load("state-fresh-load.json"))
    assert state.last_task.id is None
    assert state.last_task.type is None
    assert state.last_task.status == "idle"
    assert state.last_task.detail == ""
    assert state.vehicle is None
    assert state.mission.objective_blip is None
    # v1.2 (b): edition may still be undetermined at this point.
    assert state.bridge.edition == "unknown"
    assert state.bridge.edition in KNOWN_EDITIONS


def test_populated_state_validates_every_optional_branch() -> None:
    state = GameState.model_validate(_load("state-populated.json"))
    assert state.vehicle is not None
    assert state.vehicle.vehicle_class == "Super"  # the `class` alias resolves
    assert state.mission.objective_blip is not None
    assert state.mission.objective_blip.kind == "coord"
    assert state.nearby.vehicles and state.nearby.peds
    assert state.nearby.vehicles[0].vehicle_class == "Emergency"
    assert state.nearby.peds[0].relationship == "hostile"
    assert state.last_task.id == "t-000123"
    assert state.last_task.type == "drive_to"
    assert state.bridge.edition == "legacy"


@pytest.mark.parametrize("name", ["state-fresh-load.json", "state-populated.json"])
def test_no_field_the_bridge_sends_is_dropped_by_the_model(name: str) -> None:
    """A field the bridge emits and the harness silently ignores is a mismatch too.

    The models use extra="ignore" so a *new* bridge field cannot crash the
    harness — which also means it would never be noticed. This catches that.
    """
    sample = _load(name)
    dumped = GameState.model_validate(sample).model_dump(by_alias=True)
    missing = sorted(_keys(sample) - _keys(dumped))
    assert not missing, f"{name}: the harness model drops bridge fields {missing}"


@pytest.mark.parametrize("name", ["state-fresh-load.json", "state-populated.json"])
def test_state_survives_the_round_trip_the_prompt_does(name: str) -> None:
    """main._dynamic_context sends `model_dump_json(by_alias=True)` to the model.

    The nulls have to survive that too, or the brain is told about a task that
    does not exist.
    """
    original = GameState.model_validate(_load(name))
    reparsed = GameState.model_validate_json(original.model_dump_json(by_alias=True))
    assert reparsed == original
    payload = json.loads(original.model_dump_json(by_alias=True))
    assert payload["last_task"]["id"] == json.loads(_raw(name))["last_task"]["id"]


# --- /health -------------------------------------------------------------------


def test_health_before_the_first_tick_validates() -> None:
    health = Health.model_validate(_load("health-fresh-load.json"))
    assert health.edition == "unknown"  # v1.2 (b)
    assert health.edition in KNOWN_EDITIONS
    assert health.tick_hz == 0.0
    assert health.online_blocked is False


# --- the consumers, against the real first-poll document -----------------------


def test_every_last_task_consumer_handles_the_null_id() -> None:
    """Not just the model: the code that reads `last_task` on the first poll."""
    fresh = GameState.model_validate(_load("state-fresh-load.json"))
    populated = GameState.model_validate(_load("state-populated.json"))

    # Perception: two consecutive fresh polls must not invent a finished task.
    perceptor = Perceptor()
    first = perceptor.observe(fresh)
    assert not first.task_finished and not first.task_failed
    second = perceptor.observe(fresh)
    assert not second.task_finished, "two null task ids are not one task finishing"
    third = perceptor.observe(populated)
    assert not third.task_finished

    # Reflexes that read last_task.type / .status / .id.
    assert StuckDetector().check(fresh) is None
    assert flipped_action(fresh) is None
    assert StrandedEscalator().check(fresh) is not None  # on foot, no task: search
    assert GameRestartDetector().check(fresh) is False

    # The activity runner takes last_task.id straight from the snapshot.
    runner = ActivityRunner(ActivityPicker(random.Random(3)), random.Random(3))
    assert runner.next_step(fresh.last_task.status, fresh.last_task.id) is None


def test_a_real_task_finishing_is_still_detected() -> None:
    """The null-safety must not have blunted the actual signal."""
    running = GameState.model_validate(_load("state-populated.json"))
    done = running.model_copy(deep=True)
    done.last_task.status = "done"
    perceptor = Perceptor()
    perceptor.observe(running)
    delta = perceptor.observe(done)
    assert delta.task_finished and not delta.task_failed


# --- error codes (CONTRACTS v1.2, closed set) ----------------------------------


def _captured_errors() -> list[dict[str, Any]]:
    return _load("errors.json")["captured"]


def test_the_sample_catalog_is_the_v1_2_contract_version() -> None:
    assert _load("errors.json")["contract_version"] == "1.2"


def test_every_v1_2_error_code_is_accounted_for_by_the_bridge() -> None:
    """Both sides enumerate the same closed set."""
    captured = {e["body"]["error"] for e in _captured_errors()}
    deferred = {e["error"] for e in _load("errors.json")["not_capturable_offline"]}
    missing = sorted(set(BRIDGE_ERROR_STATUS) - captured - deferred)
    assert not missing, f"v1.2 codes the bridge never produced or documented: {missing}"


def test_recorded_error_bodies_classify_the_way_the_contract_says() -> None:
    for entry in _captured_errors():
        code = entry["body"]["error"]
        status = entry["status"]
        exc = classify_bridge_error(status, code, entry["body"]["detail"], "GET", "/state")
        if code == "online_session_active":
            assert isinstance(exc, OnlineSessionActiveError), entry["request"]
            continue
        assert isinstance(exc, BridgeApiError), entry["request"]
        assert exc.status == status and exc.error == code
        known = code in BRIDGE_ERROR_STATUS
        if known:
            # The status the bridge actually sent must match our copy of §1.
            assert BRIDGE_ERROR_STATUS[code] == status, (
                f"{code} arrived as {status}, contract says {BRIDGE_ERROR_STATUS[code]}"
            )
        should_retry = (not known) or code in TRANSIENT_BRIDGE_ERRORS
        assert isinstance(exc, BridgeTransientError) is should_retry, (
            f"{entry['request']} -> {code}: retryable={should_retry} expected"
        )


def test_startup_503s_are_transient_and_never_fatal() -> None:
    """not_ready / game_thread_stalled are the normal answers during a load."""
    by_code = {e["body"]["error"]: e for e in _captured_errors()}
    for code in ("not_ready", "game_thread_stalled"):
        assert code in by_code, f"{code} is not in the bridge's recorded errors"
        entry = by_code[code]
        exc = classify_bridge_error(
            entry["status"], code, entry["body"]["detail"], "GET", "/state"
        )
        assert isinstance(exc, BridgeTransientError)
        assert exc.status == 503


def test_an_unknown_code_is_tolerated_as_transient_not_crashed_on() -> None:
    """v1.2: 'consumers must handle unknown codes gracefully'.

    The code below is deliberately invented by this test — it is the one input
    that cannot be recorded, because by definition the bridge does not emit it
    in this contract version. It exercises the tolerance rule, nothing else.
    """
    exc = classify_bridge_error(503, "warp_core_breach", "not a v1.2 code", "GET", "/state")
    assert isinstance(exc, BridgeTransientError)
    assert exc.error == "warp_core_breach"
    assert isinstance(exc, BridgeApiError)  # still carries status/error/detail


# --- the same bodies, over a real socket, through the real client --------------


class _ReplayHandler(BaseHTTPRequestHandler):
    """Serves the bridge's recorded bytes verbatim. No harness code involved."""

    routes: ClassVar[dict[str, tuple[int, bytes]]] = {}

    def do_GET(self) -> None:  # BaseHTTPRequestHandler API name
        status, body = self.routes.get(self.path, (404, b'{"error":"not_found"}'))
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    do_POST = do_GET

    def log_message(self, *_args: Any) -> None:
        pass


@pytest.fixture
def replay_server():
    def start(routes: dict[str, tuple[int, bytes]]) -> str:
        handler = type("_H", (_ReplayHandler,), {"routes": routes})
        server = ThreadingHTTPServer(("127.0.0.1", 0), handler)
        threading.Thread(target=server.serve_forever, daemon=True).start()
        started.append(server)
        host, port = server.server_address[:2]
        return f"http://{host}:{port}"

    started: list[ThreadingHTTPServer] = []
    yield start
    for server in started:
        server.shutdown()
        server.server_close()


def test_client_parses_the_real_bytes_off_a_real_socket(replay_server) -> None:
    """End to end: bridge's recorded response bytes -> HTTP -> GameState/Health."""
    base = replay_server(
        {
            "/state": (200, _raw("state-fresh-load.json")),
            "/health": (200, _raw("health-fresh-load.json")),
        }
    )
    client = BridgeClient(base, timeout_s=2.0, connect_retries=0)
    try:
        state = client.get_state()
        assert state.last_task.id is None and state.last_task.status == "idle"
        assert client.get_health().edition == "unknown"
    finally:
        client.close()


def test_client_raises_the_right_type_for_every_recorded_error(replay_server) -> None:
    for entry in _captured_errors():
        body = json.dumps(entry["body"]).encode()
        base = replay_server({"/state": (entry["status"], body)})
        client = BridgeClient(base, timeout_s=2.0, connect_retries=0)
        code = entry["body"]["error"]
        try:
            with pytest.raises(Exception) as caught:  # exact type asserted below
                client.get_state()
        finally:
            client.close()
        exc = caught.value
        if code == "online_session_active":
            assert isinstance(exc, OnlineSessionActiveError), code
        elif code in TRANSIENT_BRIDGE_ERRORS or code not in BRIDGE_ERROR_STATUS:
            assert isinstance(exc, BridgeTransientError), code
        else:
            assert isinstance(exc, BridgeApiError), code
            assert not isinstance(exc, BridgeTransientError), code


def test_a_stalled_bridge_does_not_stop_the_client_from_recovering(replay_server) -> None:
    """not_ready then a real snapshot: the client must survive the first answer."""
    stalled = next(e for e in _captured_errors() if e["body"]["error"] == "not_ready")
    base = replay_server({"/state": (stalled["status"], json.dumps(stalled["body"]).encode())})
    client = BridgeClient(base, timeout_s=2.0, connect_retries=0)
    try:
        for _ in range(3):
            with pytest.raises(BridgeTransientError):
                client.get_state()
        # The socket is still usable afterwards — no poisoned connection.
        with pytest.raises(BridgeTransientError):
            client.get_state()
    finally:
        client.close()


def test_every_fixture_is_a_real_recording() -> None:
    """CLAUDE.md rule 1: harness/tests/fixtures/ is for real session recordings.

    This used to assert the directory was EMPTY, which was a proxy for the real rule at a time
    when no recording existed yet. Emptiness is the wrong thing to enforce now that real
    recordings live here: it would fail on exactly the fixtures rule 1 permits, while still
    passing the moment someone dropped in a hand-written file under a different extension.

    So it checks the rule itself. Every fixture must carry provenance saying which real session
    it came from and how it was captured, and no bridge contract-sample may be copied in under
    any name — those describe a shape, not a session, and a shape sample masquerading as a
    recording is precisely the invented data rule 1 exists to keep out.
    """
    fixtures = Path(__file__).resolve().parent / "fixtures"

    sample_dir = Path(__file__).resolve().parents[2] / "bridge" / "contract-samples"
    sample_names = {p.name for p in sample_dir.glob("*.json")} if sample_dir.is_dir() else set()

    for path in sorted(fixtures.glob("*.json")):
        assert path.name not in sample_names, (
            f"{path.name} is a bridge contract sample copied into the harness fixtures"
        )
        payload = json.loads(path.read_text())
        provenance = payload.get("_provenance") if isinstance(payload, dict) else None
        assert isinstance(provenance, dict), (
            f"{path.name} has no _provenance block — a fixture must say which real session it "
            f"is a recording of (CLAUDE.md rule 1)"
        )
        for field in ("session_id", "source", "captured_at"):
            assert provenance.get(field), f"{path.name}: _provenance.{field} is missing or empty"


def test_the_contract_port_is_the_one_the_client_defaults_to() -> None:
    """§1: the bridge serves http://127.0.0.1:7777."""
    client = BridgeClient()
    try:
        assert client.base_url == "http://127.0.0.1:7777"
        assert socket.gethostbyname("127.0.0.1") == "127.0.0.1"
    finally:
        client.close()
