// <auto-generated>
// GENERATED — do not edit by hand. Regenerate with:
//     bridge/tools/offline-checks/run.sh
// Source of every value below: bridge/lib/ScriptHookVDotNet3.dll
//     assembly : ScriptHookVDotNet3, Version=3.7.0.189, Culture=neutral, PublicKeyToken=null
//     sha256   : 0f2b8d30ebe79edd74cf364df3943afb7e6305d7453bc687503dcc7411ed5648
//     type     : GTA.VehicleDrivingFlags (underlying uint)
//     read with System.Reflection.MetadataLoadContext (metadata only;
//     the x64 PE is never executed on this host).
//
// DRIFT FIXTURE: DrivingModeStopForVehicles is deliberately renumbered by +1 below. This is the negative case for
// DrivingStyles.Verify() — a guard that cannot fail is not a guard,
// so the offline checks require Verify() to report drift against it.
// </auto-generated>

namespace GTA
{
    [System.Flags]
    public enum VehicleDrivingFlags : uint
    {
        None = 0,
        StopForVehicles = 1,
        StopForPeds = 2,
        SwerveAroundAllVehicles = 4,
        SteerAroundStationaryVehicles = 8,
        SteerAroundPeds = 16,
        SteerAroundObjects = 32,
        DontSteerAroundPlayerPed = 64,
        StopAtTrafficLights = 128,
        GoOffRoadWhenAvoiding = 256,
        AllowGoingWrongWay = 512,
        Reverse = 1024,
        UseWanderFallbackInsteadOfStraightLine = 2048,
        AvoidRestrictedAreas = 4096,
        PreventBackgroundPathfinding = 8192,
        AdjustCruiseSpeedBasedOnRoadSpeed = 16384,
        UseShortCutLinks = 262144,
        ChangeLanesAroundObstructions = 524288,
        UseSwitchedOffNodes = 2097152,
        PreferNavmeshRoute = 4194304,
        PlaneTaxiMode = 8388608,
        ForceStraightLine = 16777216,
        UseStringPullingAtJunctions = 33554432,
        TryToAvoidHighways = 536870912,
        ForceJoinInRoadDirection = 1073741824,
        StopAtDestination = 2147483648,
        DrivingModeStopForVehicles = 786604, // renumbered from 786603 on purpose (drift fixture)
        DrivingModeStopForVehiclesStrict = 262275,
        DrivingModeAvoidVehicles = 786469,
        DrivingModeAvoidVehiclesReckless = 786468,
        DrivingModePloughThrough = 262144,
        DrivingModeStopForVehiclesIgnoreLights = 786475,
        DrivingModeAvoidVehiclesObeyLights = 786597,
        DrivingModeAvoidVehiclesStopForPedsObeyLights = 786599,
        UseBlinkers = 256,
        FollowTraffic = 1,
        YieldToPeds = 2,
        AvoidVehicles = 4,
        AvoidEmptyVehicles = 8,
        AvoidPeds = 16,
        AvoidObjects = 32,
        AllowMedianCrossing = 262144,
        IgnorePathFinding = 16777216,
        DriveBySight = 4194304,
    }
}
