#!/usr/bin/env python3
"""Emit SQL that loads the real recorded session into a scratch database.

The fixture is a recording of an actual session pulled from the production Supabase project
(see its `_provenance` block). Nothing here invents an event, a timestamp or a payload — the rows
go in exactly as they were recorded, so settlement is tested against gameplay that really happened.

Writes SQL to stdout. Used by infra/verify-predictions.sh.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "harness" / "tests" / "fixtures" / "real_session_2026-09-04.json"


def q(s: str) -> str:
    """Single-quote a SQL literal."""
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    if not FIXTURE.exists():
        print(f"-- MISSING FIXTURE: {FIXTURE}", file=sys.stderr)
        return 1

    data = json.loads(FIXTURE.read_text())
    prov = data["_provenance"]
    events = data["events"]
    session_id = prov["session_id"]

    out: list[str] = [
        "-- Generated by scripts/load-real-session.py. Real recorded gameplay, not fabricated.",
        f"-- session {session_id}, {len(events)} events, span {prov['span'][0]} .. {prov['span'][1]}",
        "begin;",
        # The session the recording belongs to. game_edition/harness_version are required NOT NULL
        # by the base schema; these are the real values for that build.
        "insert into public.sessions (id, started_at, ended_at, game_edition, harness_version) "
        f"values ({q(session_id)}, {q(prov['span'][0])}, null, 'legacy', '0.1.0') "
        "on conflict (id) do nothing;",
    ]

    # stats carries heartbeat_at, which settlement uses as a liveness/completeness signal.
    # Set it to the last recorded event so the recording reads as "the writer caught up".
    last_ts = events[-1]["ts"]
    out.append(
        "insert into public.stats (session_id, heartbeat_at) "
        f"values ({q(session_id)}, {q(last_ts)}) "
        "on conflict (session_id) do update set heartbeat_at = excluded.heartbeat_at;"
    )

    for e in events:
        out.append(
            "insert into public.events (session_id, ts, type, payload) values ("
            f"{q(session_id)}, {q(e['ts'])}, {q(e['type'])}, {q(json.dumps(e['payload']))}::jsonb);"
        )

    out.append("commit;")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
